# Nome da GitHub Action
name: Generate Snake Animation

# Controles de quando a Action será executada
on:
  # Permite que você execute esta Action manualmente na aba "Actions"
  workflow_dispatch:
  
  # Executa a cada 12 horas
  schedule:
    - cron: "0 */12 * * *"

# Tarefas que a Action vai executar
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Gera a animação da cobrinha
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          # ID do seu usuário no GitHub
          github_user_name: ${{ github.repository_owner }}

          # Arquivos de saída
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Publica a animação gerada na branch 'output'
      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
          force_orphan: true
